[package]
name = "game"
version = "0.1.0"
authors = ["theo barollet <theo.barollet@grenoble-inp.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
engine = { path = "../engine" }
winit = "0.19"
