[package]
name = "flyskux"
version = "0.1.0"
authors = ["theo barollet <theo.barollet@grenoble-inp.org>"]
edition = "2018"

[dependencies]
vulkano = "0.12"
vulkano-shaders = "0.12"
vulkano-win = "0.12"
winit = "0.19"
