[package]
name = "flyskux"
version = "0.1.0"
authors = ["theo barollet <theo.barollet@grenoble-inp.org>"]
edition = "2018"

[dependencies]
vulkano = "0.11"
vulkano-shaders = "0.11"
vulkano-win = "0.11"
winit = "0.18"
